# commands.py

COMMANDS_LEVEL_1 = [
    "ls -la /home/user",
    "cd /var/www",
    "pwd",
    "sudo su -",
    "mkdir -p /tmp/session",
    "rm -f /tmp/file.tmp",
    'touch "/tmp/new note.txt"',
    "cp file.txt /backup/file.txt",
    "mv image.png Pictures/",
    "chmod 600 .ssh/id_rsa",
    "ssh user@192.168.0.50 -p 2222",
    "sudo apt update",
    "sudo apt upgrade -y",
    "sudo systemctl restart nginx",
    "apt update",
    "sudo apt update",
    "apt upgrade -y",
    "sudo apt upgrade -y",
    "systemctl restart nginx",
    "sudo chmod +x /usr/local/bin/script.sh",
    "reboot",
    "sudo reboot",
    "nano /etc/hosts",
    "sudo nano /etc/hosts",
    "service ssh restart",
    "sudo systemctl restart nginx",
    "useradd newuser",
    "sudo useradd newuser",
    "passwd root",
    "sudo passwd root",
    "rm -rf /var/log/*",
    "sudo rm -rf /var/log/*",
    "chown user:user /var/www/html",
    "sudo chown user:user /var/www/html",
    "chmod +x /usr/local/bin/script.sh",
    "sudo useradd newuser",
    "sudo passwd root",
    "sudo touch /root/.bashrc",
    "tar -czvf backup.tar.gz /home/user",
    "sudo tar -czvf backup.tar.gz /home/user",
    "find / -name '*.log'",
    "sudo find / -name '*.log'",
    "kill -9 1234",
    "sudo kill -9 1234",
    "su -",
    "sudo service ssh restart",
    "sudo cp /etc/hosts /etc/hosts.bak",
    "mv /tmp/file.txt /var/tmp/",
    "mkdir /opt/newdir",
    "touch /root/.bashrc",
    "tar -czvf backup.tar.gz /home/user",
    "find / -name '*.log'",
    "kill -9 1234",
    "sudo su -",
]
